package org.firstinspires.ftc.teamcode.core;

public final class LiftingSequenceStateMachine {
    public enum State { START,HOMING,SET_PLACE,PLACE_AT_FACTORY,MOVE_TO_SHELF,SELECT_LEVEL,READY1_PUSH,READY1,READY2,SCAN_RIGHT,SCAN_LEFT,CENTER_LEFT_SLOW,APPROACH_IR_SLOW,CONFIRM_IR,SAVE_SHELF_POSE,CALIBRATE_SHELF_COORDINATE,LIFT1,LIFT2,BACK_OUT_FROM_SHELF,HOLD,MOVE_NEAR_FACTORY_LEFT,PLACE_LEFT,READY1_LEFT,MOVE_TO_PLACEMENT_LEFT,HOME_LEFT,LEFT_BLOCK_RELEASED,BACK_OUT_AFTER_LEFT_RELEASE_20CM,RIGHT_RE_LIFT,MOVE_NEAR_FACTORY_RIGHT,PLACE_RIGHT,READY1_RIGHT,MOVE_TO_PLACEMENT_RIGHT,HOME_RIGHT,RIGHT_BLOCK_RELEASED,BACK_OUT_AFTER_RIGHT_RELEASE_20CM,CYCLE_COMPLETE,SAFE_STOP }
    public enum FailureCode { NONE,STOP_REQUESTED,CAMERA_STALE,POSE_INVALID,ENCODER_INVALID,NO_PROGRESS,RELEASE_UNCONFIRMED }
    public interface Clock { long nowNs(); }
    public interface Actuators {
        void stop(); boolean home(); boolean elevatorAt(LiftingSequenceConfig.ElevatorTarget target); void setFork(LiftingSequenceConfig.ForkPose pose);
        void drive(double forward,double strafe); void stopDrive(); boolean released(); double backOutDistanceCm();
        PoseReading pose(); boolean arrival(LiftingSequenceConfig.Pose target, long nowNs);
    }
    public interface CameraResult { boolean fresh(long nowNs); boolean valid(); boolean stableLeftTarget(); double leftDxPx(); }
    public static final class PoseReading { public final double x,y,heading; public final long timestampNs; public final boolean valid; public PoseReading(double x,double y,double heading,long timestampNs){this.x=x;this.y=y;this.heading=heading;this.timestampNs=timestampNs;valid=Double.isFinite(x)&&Double.isFinite(y)&&Double.isFinite(heading)&&Math.abs(heading)<=360;} }
    public static final class ShelfPose { public final int shelf,level; public final double x,y,heading; public final long timestampNs; ShelfPose(int s,int l,double x,double y,double h,long n){shelf=s;level=l;this.x=x;this.y=y;heading=h;timestampNs=n;} }
    private final Clock clock; private final Actuators actuators; private final CameraResult camera; private final LiftingSequenceConfig config; private State state=State.START; private FailureCode failure=FailureCode.NONE; private long stateStartedNs,bothIrSinceNs; private boolean stopRequested,active=true,leftIr,rightIr; private int shelf=1,level=1,completedCycles,retries; private ShelfPose shelfPose; private String leftType="01",rightType="02";
    public LiftingSequenceStateMachine(Clock c,Actuators a){this(c,a,null,null);} public LiftingSequenceStateMachine(Clock c,Actuators a,CameraResult cam){this(c,a,cam,null);} public LiftingSequenceStateMachine(Clock c,Actuators a,CameraResult cam,LiftingSequenceConfig cfg){if(c==null||a==null)throw new NullPointerException();LiftingSequenceConfig.validate();clock=c;actuators=a;camera=cam;config=cfg;stateStartedNs=c.nowNs();}
    public void setBlockTypes(String l,String r){factory(l);factory(r);leftType=l;rightType=r;} private LiftingSequenceConfig.Factory factory(String type){return config==null?LiftingSequenceConfig.factory(type):config.factoryFor(type);} public void requestStop(){stopRequested=true;} public void setActive(boolean v){active=v;} public State getState(){return state;} public FailureCode getFailure(){return failure;} public long elapsedNs(){return clock.nowNs()-stateStartedNs;} public int getShelf(){return shelf;} public int getLevel(){return level;} public int getCompletedCycles(){return completedCycles;} public int getRetries(){return retries;} public ShelfPose getShelfPose(){return shelfPose;} public void setIrState(boolean l,boolean r){leftIr=l;rightIr=r;}
    public void tick(){if(state==State.SAFE_STOP)return;long now=clock.nowNs();if(stopRequested||!active){safeStop(FailureCode.STOP_REQUESTED);return;}switch(state){
        case START: transition(State.HOMING); break; case HOMING: if(actuators.home()) transition(State.SET_PLACE); break; case SET_PLACE: actuators.setFork(LiftingSequenceConfig.ForkPose.PLACE); transition(State.PLACE_AT_FACTORY); break; case PLACE_AT_FACTORY: transition(State.MOVE_TO_SHELF); break;
        case MOVE_TO_SHELF: if(arrival(new LiftingSequenceConfig.Pose(0,0,0),now)) transition(State.SELECT_LEVEL); break; case SELECT_LEVEL: transition(level==1?State.READY1:State.READY2); break; case READY1: if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.READY1)) transition(State.SCAN_RIGHT); break; case READY2: if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.READY2)) transition(State.SCAN_RIGHT); break;
        case SCAN_RIGHT: if(cameraOk(now)) transition(State.SCAN_LEFT); break; case SCAN_LEFT: if(cameraOk(now)) transition(State.CENTER_LEFT_SLOW); break; case CENTER_LEFT_SLOW: if(!cameraOk(now)){actuators.stopDrive();safeStop(FailureCode.CAMERA_STALE);} else if(Math.abs(camera.leftDxPx())<=8){actuators.stopDrive();transition(State.APPROACH_IR_SLOW);} else actuators.drive(0,camera.leftDxPx()>0?-.08:.08); break;
        case APPROACH_IR_SLOW: if(leftIr&&rightIr){actuators.stopDrive();transition(State.CONFIRM_IR);} else actuators.drive(.08,0); break; case CONFIRM_IR: if(leftIr&&rightIr){if(bothIrSinceNs==0)bothIrSinceNs=now;if(now-bothIrSinceNs>=LiftingSequenceConfig.IR_DEBOUNCE_NS)transition(State.SAVE_SHELF_POSE);}else bothIrSinceNs=0; break;
        case SAVE_SHELF_POSE: PoseReading p=actuators.pose(); if(p==null||!p.valid){safeStop(FailureCode.POSE_INVALID);break;} shelfPose=new ShelfPose(shelf,level,p.x,p.y,p.heading,now); transition(State.CALIBRATE_SHELF_COORDINATE); break; case CALIBRATE_SHELF_COORDINATE: transition(level==1?State.LIFT1:State.LIFT2); break; case LIFT1: if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.LIFT1))transition(State.BACK_OUT_FROM_SHELF);break; case LIFT2:if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.LIFT2))transition(State.BACK_OUT_FROM_SHELF);break;
        case BACK_OUT_FROM_SHELF: if(arrival(new LiftingSequenceConfig.Pose(0,0,0),now))transition(State.HOLD);break; case HOLD:actuators.setFork(LiftingSequenceConfig.ForkPose.HOLD);transition(State.MOVE_NEAR_FACTORY_LEFT);break;
        case MOVE_NEAR_FACTORY_LEFT:if(arrival(factory(leftType).near,now))transition(State.PLACE_LEFT);break;case PLACE_LEFT:actuators.setFork(LiftingSequenceConfig.ForkPose.PLACE);transition(State.READY1_LEFT);break;case READY1_LEFT:if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.READY1))transition(State.MOVE_TO_PLACEMENT_LEFT);break;case MOVE_TO_PLACEMENT_LEFT:if(arrival(factory(leftType).placement,now))transition(State.HOME_LEFT);break;case HOME_LEFT:if(actuators.home())transition(State.LEFT_BLOCK_RELEASED);break;case LEFT_BLOCK_RELEASED:if(actuators.released())transition(State.BACK_OUT_AFTER_LEFT_RELEASE_20CM);else safeStop(FailureCode.RELEASE_UNCONFIRMED);break;case BACK_OUT_AFTER_LEFT_RELEASE_20CM:if(actuators.backOutDistanceCm()>=backOutCm()&&arrival(new LiftingSequenceConfig.Pose(0,0,0),now))transition(level==1?State.RIGHT_RE_LIFT:State.RIGHT_RE_LIFT);break; case RIGHT_RE_LIFT:if(actuators.elevatorAt(level==1?LiftingSequenceConfig.ElevatorTarget.LIFT1:LiftingSequenceConfig.ElevatorTarget.LIFT2))transition(State.MOVE_NEAR_FACTORY_RIGHT);break;
        case MOVE_NEAR_FACTORY_RIGHT:if(arrival(factory(rightType).near,now))transition(State.PLACE_RIGHT);break;case PLACE_RIGHT:actuators.setFork(LiftingSequenceConfig.ForkPose.PLACE);transition(State.READY1_RIGHT);break;case READY1_RIGHT:if(actuators.elevatorAt(LiftingSequenceConfig.ElevatorTarget.READY1))transition(State.MOVE_TO_PLACEMENT_RIGHT);break;case MOVE_TO_PLACEMENT_RIGHT:if(arrival(factory(rightType).placement,now))transition(State.HOME_RIGHT);break;case HOME_RIGHT:if(actuators.home())transition(State.RIGHT_BLOCK_RELEASED);break;case RIGHT_BLOCK_RELEASED:if(actuators.released())transition(State.BACK_OUT_AFTER_RIGHT_RELEASE_20CM);else safeStop(FailureCode.RELEASE_UNCONFIRMED);break;case BACK_OUT_AFTER_RIGHT_RELEASE_20CM:if(actuators.backOutDistanceCm()>=LiftingSequenceConfig.RELEASE_BACK_OUT_CM&&arrival(new LiftingSequenceConfig.Pose(0,0,0),now))transition(State.CYCLE_COMPLETE);break;case CYCLE_COMPLETE:completedCycles++;if(completedCycles>=6){transition(State.SAFE_STOP);}else{if(++level>2){level=1;shelf++;}transition(State.HOMING);}break;default:break;}}
    private double backOutCm(){return config==null?LiftingSequenceConfig.RELEASE_BACK_OUT_CM:config.releaseBackOutCm;} private boolean cameraOk(long n){return camera!=null&&camera.valid()&&camera.fresh(n)&&camera.stableLeftTarget();} private boolean arrival(LiftingSequenceConfig.Pose target,long n){PoseReading p=actuators.pose();if(p==null||!p.valid){safeStop(FailureCode.ENCODER_INVALID);return false;}return actuators.arrival(target,n);} private void transition(State s){state=s;stateStartedNs=clock.nowNs();retries=0;bothIrSinceNs=0;} public void safeStop(FailureCode f){failure=f;state=State.SAFE_STOP;actuators.stop();}
}
